"""add 2fa fields to user model

Revision ID: a92845c757c0
Revises: 
Create Date: 2025-04-10 19:48:54.903247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92845c757c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tf_primary_method', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tf_totp_secret', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tf_totp_secret')
        batch_op.drop_column('tf_primary_method')
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
